# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-07 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votingevent',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='votingevent_enrolled_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingevent',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votingevent_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='voted_users',
            field=models.ManyToManyField(related_name='question_voted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='voting_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.VotingEvent'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.Question'),
        ),
    ]
